// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	TintinsGetOperation      OperationName = "TintinsGet"
	TintinsIDDeleteOperation OperationName = "TintinsIDDelete"
	TintinsIDGetOperation    OperationName = "TintinsIDGet"
	TintinsIDPutOperation    OperationName = "TintinsIDPut"
	TintinsPostOperation     OperationName = "TintinsPost"
)
