// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// TintinsGet implements GET /tintins operation.
//
// Get all Tintins.
//
// GET /tintins
func (UnimplementedHandler) TintinsGet(ctx context.Context) (r []Tintin, _ error) {
	return r, ht.ErrNotImplemented
}

// TintinsIDDelete implements DELETE /tintins/{id} operation.
//
// Delete a Tintin by ID.
//
// DELETE /tintins/{id}
func (UnimplementedHandler) TintinsIDDelete(ctx context.Context, params TintinsIDDeleteParams) (r TintinsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TintinsIDGet implements GET /tintins/{id} operation.
//
// Get a Tintin by ID.
//
// GET /tintins/{id}
func (UnimplementedHandler) TintinsIDGet(ctx context.Context, params TintinsIDGetParams) (r TintinsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TintinsIDPut implements PUT /tintins/{id} operation.
//
// Update a Tintin by ID.
//
// PUT /tintins/{id}
func (UnimplementedHandler) TintinsIDPut(ctx context.Context, req *Tintin, params TintinsIDPutParams) (r TintinsIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TintinsPost implements POST /tintins operation.
//
// Create a new Tintin.
//
// POST /tintins
func (UnimplementedHandler) TintinsPost(ctx context.Context, req *Tintin) (r *Tintin, _ error) {
	return r, ht.ErrNotImplemented
}
