// Code generated by ogen, DO NOT EDIT.
package api

type TintinsIDDeleteRes interface {
	tintinsIDDeleteRes()
}

type TintinsIDGetRes interface {
	tintinsIDGetRes()
}

type TintinsIDPutRes interface {
	tintinsIDPutRes()
}
